default_backend = "gemini"

[backends.gemini]
type          = "openai"
url           = "https://generativelanguage.googleapis.com/v1beta/openai"
api_key       = "${GEMINI_API_KEY}"
default_model = "gemini-2.0-flash"
